
export const EMAIL_TYPES = {
    // Auth
    AUTH_WELCOME: 'AUTH_WELCOME',
    AUTH_GOOGLE_WELCOME: 'AUTH_GOOGLE_WELCOME',
    AUTH_EMAIL_VERIFY_OTP: 'AUTH_EMAIL_VERIFY_OTP',
    AUTH_PASSWORD_RESET: 'AUTH_PASSWORD_RESET',

    // Booking
    BOOKING_PENDING_HOST: 'BOOKING_PENDING_HOST',
    BOOKING_PENDING_GUEST: 'BOOKING_PENDING_GUEST',
    BOOKING_CONFIRMED_HOST: 'BOOKING_CONFIRMED_HOST',
    BOOKING_CONFIRMED_GUEST: 'BOOKING_CONFIRMED_GUEST',
    BOOKING_REJECTED_GUEST: 'BOOKING_REJECTED_GUEST',
    BOOKING_EXPIRED_GUEST: 'BOOKING_EXPIRED_GUEST',
    BOOKING_REMINDER_HOST: 'BOOKING_REMINDER_HOST',
    BOOKING_REMINDER_GUEST: 'BOOKING_REMINDER_GUEST',

    // Admin
    ADMIN_CNIC_VERIFIED: 'ADMIN_CNIC_VERIFIED',
    ADMIN_EMAIL_VERIFIED: 'ADMIN_EMAIL_VERIFIED',
    ADMIN_LISTING_VERIFIED: 'ADMIN_LISTING_VERIFIED',
    ADMIN_LISTING_REJECTED: 'ADMIN_LISTING_REJECTED',

    // Optional
    NEW_MESSAGE: 'NEW_MESSAGE',
    PAYMENT_CAPTURED: 'PAYMENT_CAPTURED',
    
    // Wishlist
    WISHLIST_REMINDER: 'WISHLIST_REMINDER',
    WISHLIST_DIGEST: 'WISHLIST_DIGEST',
    WISHLIST_PRICE_DROP: 'WISHLIST_PRICE_DROP',
    WISHLIST_AVAILABILITY_LOW: 'WISHLIST_AVAILABILITY_LOW',
};
